### ISSUE TITLE
Issue on python3.4

### ISSUE THREAD

**Issue by derekjc** [dropbox/pygerduty#33]
On python3.4 with the latest version of pygerduty, acknowledging an incident gives the following error. It works fine with python2.7

````
Traceback (most recent call last):
  File "oncall.py", line 35, in <module>
    incident.acknowledge(requester_id=me.id)
  File "/home/derek/pagerduty/lib/python3.4/site-packages/pygerduty/__init__.py", line 396, in acknowledge
    self._do_action('acknowledge', requester_id=requester_id)
  File "/home/derek/pagerduty/lib/python3.4/site-packages/pygerduty/__init__.py", line 390, in _do_action
    self.pagerduty.request("PUT", path, data=json.dumps(data))
  File "/home/derek/pagerduty/lib/python3.4/site-packages/pygerduty/__init__.py", line 654, in request
    return self.execute_request(request)
  File "/home/derek/pagerduty/lib/python3.4/site-packages/pygerduty/__init__.py", line 589, in execute_request
    response = (urllib.request.urlopen(request, timeout=self.timeout).
  File "/usr/lib64/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 461, in open
    req = meth(req)
  File "/usr/lib64/python3.4/urllib/request.py", line 1112, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.
````

**Comment by gmjosack** [comment]
Thanks for the report. This should be fixed in pygerduty-0.29.1.
