### ISSUE TITLE
Iterator failures in py3.8 with RuntimeError

### ISSUE THREAD

**Issue by amckenna-pinterest** [dropbox/pygerduty#85]
```
Python 3.8.0 (default, Oct 28 2019, 16:14:01)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygerduty.v2
>>> p = pygerduty.v2.PagerDuty(<api key>)
>>> for sched in p.schedules.list():
...   print(sched)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amckenna/code/venv3/lib/python3.8/site-packages/pygerduty/v2.py", line 159, in list
    this_paginated_result = self._list_no_pagination(**these_kwargs)
  File "/home/amckenna/code/venv3/lib/python3.8/site-packages/pygerduty/v2.py", line 137, in _list_no_pagination
    response = self.pagerduty.request("GET", path, query_params=kwargs)
  File "/home/amckenna/code/venv3/lib/python3.8/site-packages/pygerduty/v2.py", line 673, in request
    return self.requester.execute_request(request)
  File "/home/amckenna/code/venv3/lib/python3.8/site-packages/pygerduty/common.py", line 50, in execute_request
    response = clean_response(response)
  File "/home/amckenna/code/venv3/lib/python3.8/site-packages/pygerduty/common.py", line 68, in clean_response
    clean_response(response[key])
  File "/home/amckenna/code/venv3/lib/python3.8/site-packages/pygerduty/common.py", line 60, in clean_response
    clean_response(elem)
  File "/home/amckenna/code/venv3/lib/python3.8/site-packages/pygerduty/common.py", line 62, in clean_response
    for key, val in response.items():
RuntimeError: dictionary keys changed during iteration
```

**Comment by mcouthon** [comment]
Have you found a workaround for it?

**Comment by amckenna-pinterest** [comment]
No, we're using py3.7
